# Generated by Django 5.2.17 on 2026-10-04 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('blocked', models.BooleanField(default=False)),
                ('risk', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DatasetImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('rows', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('before', models.CharField(blank=True, max_length=100)),
                ('after', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict)),
                ('duration', models.FloatField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FraudCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Open', max_length=20)),
                ('outcome', models.CharField(blank=True, max_length=30)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.fraudcase')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('timestamp', models.IntegerField(db_index=True)),
                ('kind', models.CharField(max_length=30)),
                ('origin', models.CharField(max_length=40)),
                ('currency', models.CharField(max_length=20)),
                ('device', models.CharField(max_length=80)),
                ('failed_logins', models.IntegerField(default=0)),
                ('truth', models.BooleanField(default=False)),
                ('metadata', models.JSONField(default=dict)),
                ('features', models.JSONField(default=list)),
                ('evidence', models.JSONField(default=dict)),
                ('risk', models.IntegerField(null=True)),
                ('decision', models.CharField(default='Pending', max_length=20)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received', to='core.account')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent', to='core.account')),
            ],
            options={
                'ordering': ['-timestamp', 'id'],
            },
        ),
        migrations.AddField(
            model_name='fraudcase',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.transaction'),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forest', models.FloatField()),
                ('lof', models.FloatField()),
                ('cluster', models.IntegerField()),
                ('risk', models.IntegerField()),
                ('decision', models.CharField(max_length=20)),
                ('reasons', models.JSONField(default=list)),
                ('split', models.CharField(max_length=20)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.detectionrun')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.transaction')),
            ],
        ),
    ]
